name: GeneralEssentials
main: cjc.generalessentials.GeneralEssentials
version: 1.1
author: wjykk (Original Program), cjc (Some Updates
description: >
             General add-on that provides /kit commands.
commands:
  kit:
    description: Dispenses kits.
    usage: |
           /<command> - displays kits available.
           /<command> [kit] - dispenses kit.
